name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd main && gcc -o prism *.c  # Adjust based on your source files
    - name: Test
      run: cd main && ./prism  # Or your test command
